#!/bin/bash
set -e
checkProgram() {
    command -v "$1" &>/dev/null || { echo "program $1 not found"; exit 1; }
    command -v "$1"
}

buildwithNuitka() {
    echo "checking programs"
    echo "checking nuitka"
    nuitka=$(checkProgram "nuitka")
    echo "found nuitka"
    echo "checking source"
    srcdir=$(pwd)/src
    main="upk.py"
    outputdir="$(pwd)/output"
    echo "starting to build upk-ng"
    mkdir -p "$(pwd)/output"
    echo "building with nuitka..."
    $nuitka  --standalone --output-dir="$outputdir" --onefile "$srcdir/$main"
    mv output/upk.bin output/upk
    echo "upk executable ready at output/upk"
}



packageUpk() {
    upkbin="$(pwd)/output/upk"
    if [ ! -f "$upkbin" ]; then
        echo "please build with <<$0 build>> and then try again"
        exit 1
    fi
    
    echo "creating proper directories"
    mkdir -p "$(pwd)/package/UPK"
    mkdir -p "$(pwd)/package/usr/bin"
    mkdir -p "$(pwd)/package/var/lib/upk-ng"
    mkdir -p "$(pwd)/package/etc/upk-ng"
    cat << EOF > "$(pwd)/package/etc/upk-ng/repos"
; repository list for upk-ng
; add repos like this
; [reponame]
; server = url
[main]
server = https://juanvel4000.serv00.net/upk-ng/main
EOF
    echo "writing a manifest"
    rm -f "$(pwd)/package/UPK/info.json"
    arch=$(uname -m)
    cat << EOF > "$(pwd)/package/UPK/info.json"
{
    "name": "upk-ng",
    "version": "$1",
    "maintainer": "$2",
    "summary": "unnamed package manager - next generation",
    "architecture": "$arch"
}
EOF

    echo "packaging upk-ng"
    cp -r "$upkbin" "$(pwd)/package/usr/bin"
    "$upkbin" "build" "$(pwd)/package"
}

ver="0.2.1"

# stools
buildwithNuitka_stools() {
    echo "checking programs"
    echo "checking nuitka"
    nuitka=$(checkProgram "nuitka")
    echo "found nuitka"
    echo "checking source"
    srcdir=$(pwd)/stools
    main="stools.py"
    outputdir="$(pwd)/output"
    cat << EOF > "$srcdir/stools_info.py"
# upk-stools information file autogenerated by buildutil
rel = "$2"
version = "$1"
EOF
    echo "starting to build stools"
    mkdir -p "$(pwd)/output"
    echo "building with nuitka..."
    $nuitka  --standalone --output-dir="$outputdir/stools" --onefile "$srcdir/$main"
    mv $outputdir/stools/stools.bin output/stools/stools
    rm stools/stools_info.py
    echo "stools executable ready at output/stools/stools"
}

packagestools() {
    stlbin="$(pwd)/output/stools/stools"
    if [ ! -f "$stlbin" ]; then
        echo "please build with <<$0 build-stools>> and then try again"
        exit 1
    fi
    
    echo "creating proper directories"
    mkdir -p "$(pwd)/stools-package/UPK"
    mkdir -p "$(pwd)/stools-package/usr/bin"
    
    echo "writing a manifest"
    rm -f "$(pwd)/stools-package/UPK/info.json"
    arch=$(uname -m)
    cat << EOF > "$(pwd)/stools-package/UPK/info.json"
{
    "name": "stools",
    "version": "$1",
    "maintainer": "$2",
    "summary": "upk-ng repository/server manager",
    "architecture": "$arch"
}
EOF
    python=$(checkProgram "python3" || checkProgram "python" || checkProgram "py")
    echo "packaging stools"
    cp -r "$stlbin" "$(pwd)/stools-package/usr/bin"
    $python "./src/upk.py" "build" "$(pwd)/stools-package"
}
case "$1" in
    "build")
        buildwithNuitka
    ;;
    "build-stools")
        version="${2:-git-$(git rev-parse HEAD):-custom}"
        rel="${4:-$(git rev-parse --abbrev-ref HEAD):-Custom}"
        buildwithNuitka_stools "$version" "$rel"
    ;;
    "package")
        version="${2:-git-$(git rev-parse HEAD):-custom}"
        maintainer="${3:-$(git config --global user.name):-John Doe}"
        packageUpk "$version" "$maintainer"
    ;;
    "package-stools")
        version="${2:-git-$(git rev-parse HEAD):-custom}"
        maintainer="${3:-$(git config --global user.name):-John Doe}"
        packagestools "$version" "$maintainer"
    ;;
    "help")
        echo "usage: $0 [options]"
        echo "upk-ng/stools build utility"
        echo " options:"
        echo "   help                               - show this message"
        echo "   build <ver> <maintainer> <rel>     - use nuitka to build a standalone binary in the output/ folder"
        echo "   package <ver> <maintainer>         - create a upk-ng package you can later install with upk" 
        echo "   build-stools <ver> <rel>           - use nuitka to build a standalone binary in the output/ folder"
        echo "   package-stools <ver> <maintainer>  - create a upk-ng package you can later install with upk" 
        echo "   clean                              - clean output/ (warning: this may slow the next build)"
        echo "upk-ng/stools buildutil $ver"
    ;;
    "clean")
        echo "cleaning up..."
        
        if [ -d "$(pwd)/output" ]; then
            rm -rv "$(pwd)/output/*" >> "cleanLog"
            read -rp "Do you want to see the deleted files? [y/N] " willview
            case "$willview" in
                [Yy]) cat cleanLog && rm cleanLog ;;
                *) rm cleanLog ;;
            esac
            echo "cleaned output directory"
        else
            echo "output directory does not exist."
            exit 1
        fi
    ;;
    *)
        echo "usage: $0 [build|package](-stools) or [help|clean]"
        exit 1
    ;;
esac
